<?php 
// Получаем коллекцию продуктов и ID категории
$collection = $block->getProductCollection();
$categoryId = $block->getCategoryId(); // Получаем ID категории
?>

<!-- Выводим ID выбранной категории -->
<p>Selected Category ID: <?php echo $categoryId; ?>!!!</p>

<?php if ($collection instanceof \Magento\Catalog\Model\ResourceModel\Product\Collection): ?>
    <!-- Проверяем, что коллекция найдена -->
    <?php if ($collection->getSize()): ?>
        <ul>
            <?php foreach ($collection as $product): ?>
                <li>
                    <a href="<?php echo $product->getProductUrl(); ?>">
                        <?php echo $product->getName(); ?>
                    </a>
                    <p><?php echo $product->getPrice(); ?> $</p>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <p>No products found in this category.</p>
    <?php endif; ?>
<?php else: ?>
    <p>Category not found.</p>
<?php endif; ?>
